language: node_js
node_js:
  - "6"
before_install:  
  - npm install -g npm
before_script:
  - npm install -g gulp
script:
  - gulp test

after_success:
- ./node_modules/.bin/jscoverage lib lib-cov
- ./node_modules/.bin/mocha jasmine/spec/**.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js