language: node_js
node_js:
  - "6"
before_install:  
  - npm install -g npm
before_script:
  - npm install -g gulp
script:
  - gulp test

after_success: istanbul cover jasmine-node --captureExceptions spec/ && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
